### ISSUE TITLE
Astro integration doesn't take `paths` into account

### ISSUE THREAD

**Issue by laymonage** [JulianCataldo/og-images-generator#2]
Thank you for this package! I tried to use the Astro integration and it works great locally, but sadly I can't get it to work when deploying to Vercel with a hybrid/SSR mode. The reason is that the integration does not take the `paths` configuration into account. It calls `generateOgImages` without any parameters here:

https://github.com/JulianCataldo/og-images-generator/blob/be04b8cff19a18b946e3f6d8a7afea96ee5269e5/src/plugins/astro-integration.js#L15

So the function always uses the default values with the `dist` prefix:

https://github.com/JulianCataldo/og-images-generator/blob/be04b8cff19a18b946e3f6d8a7afea96ee5269e5/src/generate.js#L88-L95

Vercel's integration for Astro uses a different build directory, i.e. `./.vercel/output/static/` instead of `./dist` (at least when not fully SSG). I already specified it as the `paths` exported variable in my `og-images-config.js`, but it doesn't get picked up due to the above code.

Could you make it so that the Astro integration reads the `path` config too? Thanks!

**Comment by JulianCataldo** [comment]
Hello, thank you very much for your report.
I don't use Serverless much, only Node, sometimes Deno/Bun for fun/experiments.

Would you mind taking a stab at this and create a PR?

**Comment by JulianCataldo** [comment]
With 0.3.0, you can now forward options to all kind of plugins, and you have a new `additionalPatterns` options for the globber to consume. Useful for negated patterns, to exclude unwanted HTML files.

**Comment by laymonage** [comment]
Thank you very much, now it works as expected! 🥳
